name: Build & Publish to NPM and GHP

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types:
      - closed
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: docker://pandoc/core:2.9
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          sudo apt-get install -y xfonts-base xfonts-75dpi
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.bullseye_arm64.deb
          sudo dpkg -i wkhtmltox_0.12.6.1-2.bullseye_arm64.deb
      - run: npm ci
      - run: npm test