
# https://github.com/pandoc/pandoc-action-example
# https://github.com/actions/runner-images/issues/482#issuecomment-806539083
# https://github.com/wkhtmltopdf/packaging/releases

name: Build & Publish to NPM and GHP

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
    types:
      - closed
    paths:
      - 'package.json'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: docker://pandoc/core:2.9
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo apt-get install -y wkhtmltopdf
      - run: npm ci
      - run: npm test